server:
  port: 8922
spring:
  datasource:
    master:
      password: root
      url: jdbc:mysql://localhost:3306/master?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&characterSetResults=UTF-8&&amp;allowMultiQueries=true&amp;useServerPrepStmts=false&amp;rewriteBatchedStatements=true&amp;zeroDateTimeBehavior=convertToNull&autoReconnectForPools=true&allowMultiQueries=true&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      type: com.zaxxer.hikari.HikariDataSource
    cluster:
      - key: slave1
        password: root
        url: jdbc:mysql://localhost:3306/slave1?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&characterSetResults=UTF-8&&amp;allowMultiQueries=true&amp;useServerPrepStmts=false&amp;rewriteBatchedStatements=true&amp;zeroDateTimeBehavior=convertToNull&autoReconnectForPools=true&allowMultiQueries=true&useSSL=false
        idle-timeout: 20000
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        type: com.zaxxer.hikari.HikariDataSource
      - key: slave2
        password: root
        url: jdbc:mysql://localhost:3306/slave2?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&characterSetResults=UTF-8&&amp;allowMultiQueries=true&amp;useServerPrepStmts=false&amp;rewriteBatchedStatements=true&amp;zeroDateTimeBehavior=convertToNull&autoReconnectForPools=true&allowMultiQueries=true&useSSL=false
        idle-timeout: 20000
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql

logging:
  level:
    com:
      yukong:
        chapter5:
          repository: debug